### ISSUE TITLE
2.2.0.0 - Client crashing after issue with broadcasting to network.

### ISSUE THREAD

**Issue by Th3-Cap3** [nguyenquyhy/Flight-Events#10]
Hello! I wanted to post this here for you guys to see if you have an answer or fix for what I am seeing with the current release.

Upon launching the new client I went to go configure it for use with Foreflight by checking the "Broadcast data to local network" option. Upon clicking said option, it looks like the check box flickers between being set and not being set very rapidly until the client eventually crashes.

During the time the option appears to be flashing, it looks like the preferences.json and preferences.json.bak files are repeatedly deleted and created, almost like the program was trying to read the file, couldn't then was like "I'll just make a new one".

Things I have tried to see if I could get it to work.
- Downloaded a new fresh copy from Github
- Disabled AV
- Run the client as admin
- Run client as admin while AV was disabled
- Multiple PC restarts
- Attempted to open the client at different times (before MSFS opened, after, while in flight, etc...)
- Tried launching with the multiple-instances flag

Funny thing though, is while it's going back and forth trying to figure out what to do, it does work and broadcasts the data, I can see my flight in Foreflight on my iPad, up until the program crashes.

Appreciate the work you folks are doing! I've attached the log file from my attempt to run it today.
[flightevents20200928.zip](https://github.com/nguyenquyhy/Flight-Events/files/5292624/flightevents20200928.zip)

**Comment by nguyenquyhy** [comment]
I notice this issue too. I'll fix it in the next update.

**Comment by Th3-Cap3** [comment]
Hey @nguyenquyhy , awesome! let me know if you need me to do any testing or additional logs, happy to help if I can. Cheers!

**Comment by nguyenquyhy** [comment]
Thanks. Your log has all the details I need.

This should be fixed in 935b2f6 and released in version 2.2.1.
