### ISSUE TITLE
Flight Event Bot is offline

### ISSUE THREAD

**Issue by August78** [nguyenquyhy/Flight-Events#22]
Hi. We are a group of bushpilots who would love to use the flight event bot to help with voice communication during flight events. However, we are a bit noob, and we don't know all the features of discord etc, but to us it seems that the bot is offline. Is this because of our user error, or is the bot actually not functioning at the moment?

**Comment by nguyenquyhy** [comment]
Really sorry. It should be up now. Many thanks for letting me know.
I have been trying to fix that in the previous weeks but got caught with some other thing. I'll try to improve this situation this weekend.

**Comment by August78** [comment]
You are awesome! Barely had time to hit submit before you solved the problem. thank you so much :)

**Comment by August78** [comment]
Question: We have an existing discord channel with many categories and channels. We cant seem to get flight event bot into this category and the lounge voice channel we created for it. How do we do this? When I click invite on the channel to pick the bot, it doesnt show up on the list.

**Comment by nguyenquyhy** [comment]
Have you followed the guide I put here https://github.com/nguyenquyhy/Flight-Events/blob/master/SERVER.md ?

**Comment by August78** [comment]
Yes, but it is still puzzling to us :) As I said, we are a bit newbi to discord. We gave the bot a "bot" role, and set the permissions to the bot role in the channel according to your guide. When I connect with the FE client (and I have authorized the app in discord), the bot doesnt move me to a separate channel according to what I have in my cockpit?

**Comment by nguyenquyhy** [comment]
Did you skip step 4 though ;)?

**Comment by August78** [comment]
Oh what do you know. No didnt see that part. Ive been scourering the guide for a discord link but cant find a link to you?

**Comment by nguyenquyhy** [comment]
You can find me (Hy) in MSFS Discord server, or join a small server I just created https://discord.gg/Pd6qq3qS.

**Comment by nguyenquyhy** [comment]
Closing this as we don't seem to get any new information. Please feel free to reopen if this still happens.
