### ISSUE TITLE
PLEASE HELP for FlightTracker.tech Call-sign change???

### ISSUE THREAD

**Issue by ThunderRod7** [nguyenquyhy/Flight-Events#23]
G'day from Down Under,

I am wondering if anyone knows how to change ones Call-sign in flighttracker.tech. Maybe I am blind but I cannot find anywhere to change it. Can anyone PLEASE HELP?
Thank You 
Mal

**Comment by nguyenquyhy** [comment]
You just stop tracking and change it in the client.
