### ISSUE TITLE
MSFS2020 SimConnect not found

### ISSUE THREAD

**Issue by RSCG2017** [nguyenquyhy/Flight-Events#24]
I just built my PC to runMSFS2020 (working fine). I have a foreflight subscription( loged into  the foreflight on my PC and iPad and working fine). I have done all the steps needed to DL and connect foreflight to my PC MSFS 2020. When I launch the Flightevents.cient ver 2.5.0.0 is gives this ERROR: Needed component is missing  Sim connect is not found. This component is needed to connect to flight simulaor. Please make sure you have installed Microsoft Flight Simulator and restart the client.

IM ABOUT TO FIX THISS  WITH A HAMMER!!!!!!!!!!!!!!!!!!!!!!!!!!

**Comment by nguyenquyhy** [comment]
I have seen some having this issue and I am trying to figure that one out. By right SimConnect should be installed automatically with MSFS. Are you using the version from Steam or Microsoft Store?

**Comment by domFS** [comment]
I have had a similar problem.  I have reinstalled Windows and MSFS, and the problem has not gone away.  I have attached the FlightEvents log file.  Can you help me?
[flightevents20210626.log](https://github.com/nguyenquyhy/Flight-Events/files/6720464/flightevents20210626.log)

**Comment by nguyenquyhy** [comment]
I have found the issue and released a fix before. Please let me know if anyone still have this problem.
