### ISSUE TITLE
Flight Events off MSFS screen

### ISSUE THREAD

**Issue by psuchuck** [nguyenquyhy/Flight-Events#27]
I saw Flight Events pop up on the very extreme right corner of MSFS.  I am unable to bring it into the view.  Looking for help how to get it into view so I can use it.  Thanks.

**Comment by nguyenquyhy** [comment]
Can you give a screenshot? It's a bit hard to imagine the issue 😛.

**Comment by psuchuck** [comment]
Well that's strange, when I just went to take a screenshot, it started working.  So all appears OK.  If it does it again, I'll post a photo.     What a great tool, nice job with this!

**Comment by nguyenquyhy** [comment]
All bugs are scared of screenshots 😂.
