### ISSUE TITLE
program window a little bit too small

### ISSUE THREAD

**Issue by icebird4all** [nguyenquyhy/Flight-Events#29]
Hello Hy!

Since the last update the program window is a little bit too small to see all of the content!

Thx for the nice progi - so far!

Best - Klaus
![Screen_2021 04 10_18_49_25](https://user-images.githubusercontent.com/82281924/114278179-da811d80-9a2e-11eb-8324-bdcab588c2c4.jpg)
![Screen_2021 04 10_18_50_42](https://user-images.githubusercontent.com/82281924/114278183-de14a480-9a2e-11eb-903e-a2a0d65192ac.jpg)

**Comment by boomcreeper11** [comment]
You aren't on the latest version

**Comment by nguyenquyhy** [comment]
Please let me know if you still have this issue. I have released several fixes for this but I am not sure if this is fixed for everyone.

**Comment by icebird4all** [comment]
its good for me - thx!
