### ISSUE TITLE
Discord Bot Setup I don't know your account name or hash number

### ISSUE THREAD

**Issue by boomcreeper11** [nguyenquyhy/Flight-Events#33]
When setting up your discord bot step four asks that I Pm you on Discord with your server ID, category ID, lounge channel ID and command channel ID (if used) but I can't do that because I'm not in a server with you nor do I know your username and number.

**Comment by nguyenquyhy** [comment]
Here is our Discord server https://discord.gg/azqQrWWEbV. Feel free to pm me there.

**Comment by boomcreeper11** [comment]
oh thanks
