### ISSUE TITLE
SimConnect MS FSX and ForeFlight

### ISSUE THREAD

**Issue by HFCPilot** [nguyenquyhy/Flight-Events#36]
I tried unsuccessfully to run the FSX Flight Event client.  I keep getting a SimConnect missing.  I see the DLL in my FSX folder.  I am running W10.

**Comment by rkantos** [comment]
Is still an issue for you? Did you have all the versions of SimConnect installed?

https://downloads.justflight.com/support/simconnect/SimConnectESP.msi
https://downloads.justflight.com/support/simconnect/SimConnectRTM.msi
https://downloads.justflight.com/support/simconnect/SimConnectSP1.msi
https://downloads.justflight.com/support/simconnect/SimConnectXPACK.msi

AFAIK the FSX version of FlightEvents required SP1 and/or the XPACK version of SimConnect.
