### ISSUE TITLE
stream to foreflight via internet

### ISSUE THREAD

**Issue by 9-FS** [nguyenquyhy/Flight-Events#45]
I play Flight Simulator on a shadow cloud computer, so outside of my local network, and would still like to connect the simulator to my local foreflight app.
Would be great if the existing local IP input could also just take my local networks IP or something to stream to the correct device. Thank you!

**Comment by nguyenquyhy** [comment]
You can try to port forward to your sim PC, and set the IP as your PC public IP. This is purely network infrastructure setup and not something Flight Event can control unfortunately.

**Comment by 9-FS** [comment]
This worked!! Many thanks!

For anyone having the same problem:
- In your router, activate port forwarding for your iPad or other local device.
- Go to https://www.whatismyip.com/ and enter your local network's IPv4 into your remote Flight Events client as destination address.

**Comment by nguyenquyhy** [comment]
I was about to correct myself that you have to port forward to the iPad instead of the sim PC, but looks like you have figured that out 😂.
