### ISSUE TITLE
Foreflight problem

### ISSUE THREAD

**Issue by N1215S** [nguyenquyhy/Flight-Events#46]
I am a student pilot, and I am using FlightEvents to connect MSFS 2020 to my ipad with ForeFlight.   The problem is that while Foreflight it tracking my flight on MSFS 2020, it also keeps moving my position in Forefligjht from the flight position on MSFS 2020 to my actual "real" position where my house and computer are located.   This means that my green progress line line (breadcrumb line) on Foreflight keeps going back and forth between my real positon and my aircraft position on MSFS.   I have tried turning off the location option in Foreflight, but that does not work because Foreflight needs location turned on to work with FligjhtEvents and MSFS 2020.    Do you have any suggestions as to how to stop this problem?  Thanks for any help that you can give me.

**Comment by nguyenquyhy** [comment]
I believe you don't need iPad location for Flight Events integration. Flight Events should show as a device in the Devices list in ForeFlight.

**Comment by nguyenquyhy** [comment]
Closing this as we don't seem to get any new information. Please feel free to reopen if this still happens.
