### ISSUE TITLE
Is Flight tracker still real? 

### ISSUE THREAD

**Issue by Kabouterplons** [nguyenquyhy/Flight-Events#47]
Is Flight tracker still real? The last update was a long time ago.... I would really like to use it with the ingame panel.
It works for me in the browser but the in game toolbar panel does not work. A white square appears in the toolbar, but no icon. Clicking on it does not produce a map panel....
I put the folder "nguyenquyhy-ingamepanels-flightevents" in the community folder.

**Comment by nguyenquyhy** [comment]
I have not updated the panel for a while. I'll check this later.

**Comment by Kabouterplons** [comment]
Have you looked at my described problem?

Tnx, Fer

**Comment by nguyenquyhy** [comment]
I published a new version 0.3.0. Can you please try again with that?

I am currently on Sim Update 10, so I am not too sure if it would work properly in previous updates.
