### ISSUE TITLE
Add Font size for smaller screens

### ISSUE THREAD

**Issue by RodoxVR** [nguyenquyhy/Flight-Events#60]
Just some Feedback,

I'm using the NZXT Kraken 360 elite cpu cooler and it has a little screen on it, very cool that i can use Web Integration to show were i am flying, 

Can we get an option to make font larger to read easier what city/village im flying over.

Thanks, stay awesome.

**Comment by nguyenquyhy** [comment]
Your setup sounds awesome. I think this feature might already be there with a custom parameter in the URL. Let me get back to you once I get to my computer.

**Comment by RodoxVR** [comment]
Alright, take your time :)


Op za 20 mei 2023 om 01:34 schreef Nguyễn Quý Hy ***@***.***>:

**Comment by nguyenquyhy** [comment]
This is done. Please try to use this URL:
https://events.flighttracker.tech/?scaling=2

**Comment by nguyenquyhy** [comment]
Btw, you can also add mode parameter to hide other controls:
https://events.flighttracker.tech/?scaling=2&mode=none

I have a bunch more if you are interested in putting parameters in the URL instead of clicking on the page.

**Comment by RodoxVR** [comment]
Perfect, this is great... thank you :)
