### ISSUE TITLE
FlightEvents.Client.exe fails to open when double clicked. It was working fine yesterday

### ISSUE THREAD

**Issue by markthomas88** [nguyenquyhy/Flight-Events#72]
I started using flight events tracker yesterday, and it was working great with FS2020 and Foreflight. Now, the client won't open at all. I even re-downloaded it, and the new one will also not open. The first time running, I clicked "More options" and Run Anyway. I also turned off Windows Defender completely. It still won't open. I really wanted to show my flying instructor my flight log from foreflight but I'm wasting so much time just trying to fix this.

**Comment by nguyenquyhy** [comment]
I tried the current version and some old version and can't reproduce the crash so I think it's not a server issue. Would you might pm me (Hy) in my Discord server? 
Invite link: https://discord.gg/azqQrWWEbV

**Comment by nguyenquyhy** [comment]
I just released an update with a few crash fixes. Would you please try it and let me know if it helps?
