### ISSUE TITLE
In Game Map Not working

### ISSUE THREAD

**Issue by djmarko413** [nguyenquyhy/Flight-Events#75]
This just started recently. I believe it coincides with the last MSFS update I did. When I open the in game map I get the following text in the map "https://events.flighttracker.tech/static/js/2.4cd6fdc1.chunk.js 2 1363780 ReferenceError: Can't find variable:globalThis". The map in the browser works fine. This is occurring in separate MSFS installations both of which were recently updated. I reinstalled both the client and the in game panel but no luck.

**Comment by nguyenquyhy** [comment]
Thanks for letting me know. I think it is because I tried to update a few things on the site to a more updated version, and ended up breaking the panel because the browser runtime in MSFS is quite limited. I'll try to see if I can find a workaround for it somehow.

**Comment by nguyenquyhy** [comment]
This is now fixed. Please try again.

**Comment by djmarko413** [comment]
Yes indeed, it is now working again.  Thank you so much for all your work on this. I love this feature and use it on every flight.

**Comment by nguyenquyhy** [comment]
I would also suggest to update the client if you have a chance. I updated it to 2.7.4 for a bunch of crash fixes.

**Comment by djmarko413** [comment]
Thanks again, I absolutely will update.

**Comment by MicroMidi** [comment]
May I ask where I can download the current version of the In Game Panel?

**Comment by djmarko413** [comment]
Go to https://events.flighttracker.tech/. Click on Join in the upper right corner and you will see the option to download the tool bar panel.

**Comment by MicroMidi** [comment]
@djmarko413; Thanks so much for the fast reply - and the simple solution🙏. This tool is one of my essentials in MSFS and I was afraid that this is now finally broken...
@nguyenquyhy: What a great tool - and  a very talented developer. Thanks for all your time and effort👌😊

**Comment by djmarko413** [comment]
I’m glad I could help.
