### ISSUE TITLE
How to use broadcast data to local network feature

### ISSUE THREAD

**Issue by kucukkanat** [nguyenquyhy/Flight-Events#8]
How can I use flghttracker to broadcast data to local network? 
I tried typing local IP and the port of my UDP server that listens to incoming data but I received no data

**Comment by nguyenquyhy** [comment]
If you leave the IP textbox empty, it will perform UDP broadcast to the whole network. However, that is up to how (or if) your router supports UDP multicast.

If you type in the IP of your UDP listener, and the network configuration allows the 2 computers to see each other, the packet should get sent. Again, this also up to your router configuration. Maybe try to Wireshark on the Flight Events PC and the UDP server and see if the packets get sent?

Also, remember to Start Flight Tracking in the first tab and tick broadcast data in the last tab.
